# Maven
# Builds project and runs automated tests
# Eider Mauricio Aristizabal Erazo

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'calculator2'
    organization: '19dc366175d22a9587bf88598ab962bbaa5f3651'
    scannerMode: 'Other'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    sonarQubeRunAnalysis: true
    goals: 'install'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
